import type { Metadata } from "next";
import {  Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({subsets: ["latin"], weight: "700"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className + " h-screen w-screen"}>{children}</body>
    </html>
  );
}
